[project]
name = "neurofighter-nds-server"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "fastapi[standard]>=0.121.3",
    "numpy>=2.3.3",
    "polars>=1.35.2",
    "torch>=2.9.1",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"
